plugins {
    id 'com.android.application'
}

android {
    namespace 'vn.vedax.hardwaretest'
    compileSdk 35

    buildFeatures {
        buildConfig true
    }

    defaultConfig {
        applicationId 'vn.vedax.hardwaretest'
        minSdk 26
        targetSdk 32
        versionCode 4
        versionName '0.3.1'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    applicationVariants.all { variant ->
        variant.outputs.all { output ->
            output.outputFileName = "VedaX-Hardware-Test-v${variant.versionName}-${variant.buildType.name}.apk"
        }
    }
}
