plugins {
    id 'com.android.application'
}

android {
    namespace 'vn.vedax.hardwaretest'
    compileSdk 35

    buildFeatures {
        buildConfig true
    }

    defaultConfig {
        applicationId 'vn.vedax.hardwaretest'
        minSdk 26
        targetSdk 32
        versionCode 3
        versionName '0.3.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
